// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: gbProto.proto

package gbp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid string `protobuf:"bytes,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Sid string `protobuf:"bytes,2,opt,name=Sid,proto3" json:"Sid,omitempty"`
	Msg string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{0}
}

func (x *ChatPayload) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *ChatPayload) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *ChatPayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Transport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []byte `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Tp  int32  `protobuf:"varint,3,opt,name=Tp,proto3" json:"Tp,omitempty"`
}

func (x *Transport) Reset() {
	*x = Transport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{1}
}

func (x *Transport) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transport) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

type MsgFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  string `protobuf:"bytes,1,opt,name=Sid,proto3" json:"Sid,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Mloc string `protobuf:"bytes,3,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *MsgFormat) Reset() {
	*x = MsgFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFormat) ProtoMessage() {}

func (x *MsgFormat) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFormat.ProtoReflect.Descriptor instead.
func (*MsgFormat) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{2}
}

func (x *MsgFormat) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *MsgFormat) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgFormat) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type RecvNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	MId string `protobuf:"bytes,2,opt,name=MId,proto3" json:"MId,omitempty"`
	Tp  int32  `protobuf:"varint,3,opt,name=Tp,proto3" json:"Tp,omitempty"`
}

func (x *RecvNotify) Reset() {
	*x = RecvNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvNotify) ProtoMessage() {}

func (x *RecvNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvNotify.ProtoReflect.Descriptor instead.
func (*RecvNotify) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{3}
}

func (x *RecvNotify) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *RecvNotify) GetMId() string {
	if x != nil {
		return x.MId
	}
	return ""
}

func (x *RecvNotify) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

type SendNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TMid string `protobuf:"bytes,1,opt,name=TMid,proto3" json:"TMid,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendNotify) Reset() {
	*x = SendNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotify) ProtoMessage() {}

func (x *SendNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotify.ProtoReflect.Descriptor instead.
func (*SendNotify) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{4}
}

func (x *SendNotify) GetTMid() string {
	if x != nil {
		return x.TMid
	}
	return ""
}

func (x *SendNotify) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MId  string `protobuf:"bytes,1,opt,name=MId,proto3" json:"MId,omitempty"`
	MLoc string `protobuf:"bytes,2,opt,name=MLoc,proto3" json:"MLoc,omitempty"`
}

func (x *ChatAck) Reset() {
	*x = ChatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAck) ProtoMessage() {}

func (x *ChatAck) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAck.ProtoReflect.Descriptor instead.
func (*ChatAck) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{5}
}

func (x *ChatAck) GetMId() string {
	if x != nil {
		return x.MId
	}
	return ""
}

func (x *ChatAck) GetMLoc() string {
	if x != nil {
		return x.MLoc
	}
	return ""
}

type SaveFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tp   int32  `protobuf:"varint,1,opt,name=Tp,proto3" json:"Tp,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SaveFormat) Reset() {
	*x = SaveFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFormat) ProtoMessage() {}

func (x *SaveFormat) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFormat.ProtoReflect.Descriptor instead.
func (*SaveFormat) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{6}
}

func (x *SaveFormat) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *SaveFormat) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HandShackP1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetMobile string `protobuf:"bytes,1,opt,name=TargetMobile,proto3" json:"TargetMobile,omitempty"`
	SenderMID    string `protobuf:"bytes,2,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
	PublicKey    string `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Hsid         string `protobuf:"bytes,4,opt,name=Hsid,proto3" json:"Hsid,omitempty"`
	Mloc         string `protobuf:"bytes,5,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *HandShackP1) Reset() {
	*x = HandShackP1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandShackP1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandShackP1) ProtoMessage() {}

func (x *HandShackP1) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandShackP1.ProtoReflect.Descriptor instead.
func (*HandShackP1) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{7}
}

func (x *HandShackP1) GetTargetMobile() string {
	if x != nil {
		return x.TargetMobile
	}
	return ""
}

func (x *HandShackP1) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

func (x *HandShackP1) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *HandShackP1) GetHsid() string {
	if x != nil {
		return x.Hsid
	}
	return ""
}

func (x *HandShackP1) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type HandShackP2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedData string `protobuf:"bytes,1,opt,name=EncryptedData,proto3" json:"EncryptedData,omitempty"`
	TargetMID     string `protobuf:"bytes,2,opt,name=TargetMID,proto3" json:"TargetMID,omitempty"`
	SenderMID     string `protobuf:"bytes,3,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
	Hsid          string `protobuf:"bytes,4,opt,name=Hsid,proto3" json:"Hsid,omitempty"`
	Mloc          string `protobuf:"bytes,5,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
	Permit        int32  `protobuf:"varint,6,opt,name=Permit,proto3" json:"Permit,omitempty"`
}

func (x *HandShackP2) Reset() {
	*x = HandShackP2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandShackP2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandShackP2) ProtoMessage() {}

func (x *HandShackP2) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandShackP2.ProtoReflect.Descriptor instead.
func (*HandShackP2) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{8}
}

func (x *HandShackP2) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

func (x *HandShackP2) GetTargetMID() string {
	if x != nil {
		return x.TargetMID
	}
	return ""
}

func (x *HandShackP2) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

func (x *HandShackP2) GetHsid() string {
	if x != nil {
		return x.Hsid
	}
	return ""
}

func (x *HandShackP2) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

func (x *HandShackP2) GetPermit() int32 {
	if x != nil {
		return x.Permit
	}
	return 0
}

type ConnDataTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Number     string `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	MID        string `protobuf:"bytes,3,opt,name=MID,proto3" json:"MID,omitempty"`
	ProfilePic string `protobuf:"bytes,4,opt,name=ProfilePic,proto3" json:"ProfilePic,omitempty"`
	Hsid       string `protobuf:"bytes,5,opt,name=Hsid,proto3" json:"Hsid,omitempty"`
	Mloc       string `protobuf:"bytes,6,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *ConnDataTransfer) Reset() {
	*x = ConnDataTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnDataTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnDataTransfer) ProtoMessage() {}

func (x *ConnDataTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnDataTransfer.ProtoReflect.Descriptor instead.
func (*ConnDataTransfer) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{9}
}

func (x *ConnDataTransfer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnDataTransfer) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ConnDataTransfer) GetMID() string {
	if x != nil {
		return x.MID
	}
	return ""
}

func (x *ConnDataTransfer) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

func (x *ConnDataTransfer) GetHsid() string {
	if x != nil {
		return x.Hsid
	}
	return ""
}

func (x *ConnDataTransfer) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type HandshakeDeleteNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderMID string `protobuf:"bytes,1,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
	TargetMID string `protobuf:"bytes,2,opt,name=TargetMID,proto3" json:"TargetMID,omitempty"`
	Number    string `protobuf:"bytes,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Mloc      string `protobuf:"bytes,4,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *HandshakeDeleteNotify) Reset() {
	*x = HandshakeDeleteNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeDeleteNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeDeleteNotify) ProtoMessage() {}

func (x *HandshakeDeleteNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeDeleteNotify.ProtoReflect.Descriptor instead.
func (*HandshakeDeleteNotify) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{10}
}

func (x *HandshakeDeleteNotify) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

func (x *HandshakeDeleteNotify) GetTargetMID() string {
	if x != nil {
		return x.TargetMID
	}
	return ""
}

func (x *HandshakeDeleteNotify) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *HandshakeDeleteNotify) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type ChangeProfilePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PicData   string `protobuf:"bytes,1,opt,name=PicData,proto3" json:"PicData,omitempty"`
	SenderMID string `protobuf:"bytes,2,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
	TargetMID string `protobuf:"bytes,3,opt,name=TargetMID,proto3" json:"TargetMID,omitempty"`
	Mloc      string `protobuf:"bytes,4,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *ChangeProfilePayload) Reset() {
	*x = ChangeProfilePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeProfilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProfilePayload) ProtoMessage() {}

func (x *ChangeProfilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProfilePayload.ProtoReflect.Descriptor instead.
func (*ChangeProfilePayload) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeProfilePayload) GetPicData() string {
	if x != nil {
		return x.PicData
	}
	return ""
}

func (x *ChangeProfilePayload) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

func (x *ChangeProfilePayload) GetTargetMID() string {
	if x != nil {
		return x.TargetMID
	}
	return ""
}

func (x *ChangeProfilePayload) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type ChangeProfilePayloads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All       []string `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	PicData   string   `protobuf:"bytes,2,opt,name=PicData,proto3" json:"PicData,omitempty"`
	SenderMID string   `protobuf:"bytes,3,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
}

func (x *ChangeProfilePayloads) Reset() {
	*x = ChangeProfilePayloads{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeProfilePayloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProfilePayloads) ProtoMessage() {}

func (x *ChangeProfilePayloads) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProfilePayloads.ProtoReflect.Descriptor instead.
func (*ChangeProfilePayloads) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeProfilePayloads) GetAll() []string {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *ChangeProfilePayloads) GetPicData() string {
	if x != nil {
		return x.PicData
	}
	return ""
}

func (x *ChangeProfilePayloads) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

type NotifyChangeNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number    string `protobuf:"bytes,1,opt,name=Number,proto3" json:"Number,omitempty"`
	SenderMID string `protobuf:"bytes,2,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
	TargetMID string `protobuf:"bytes,3,opt,name=TargetMID,proto3" json:"TargetMID,omitempty"`
	Mloc      string `protobuf:"bytes,4,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *NotifyChangeNumber) Reset() {
	*x = NotifyChangeNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyChangeNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChangeNumber) ProtoMessage() {}

func (x *NotifyChangeNumber) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChangeNumber.ProtoReflect.Descriptor instead.
func (*NotifyChangeNumber) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyChangeNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *NotifyChangeNumber) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

func (x *NotifyChangeNumber) GetTargetMID() string {
	if x != nil {
		return x.TargetMID
	}
	return ""
}

func (x *NotifyChangeNumber) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type NotifyChangeNumbers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All       []string `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	Number    string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	SenderMID string   `protobuf:"bytes,3,opt,name=SenderMID,proto3" json:"SenderMID,omitempty"`
}

func (x *NotifyChangeNumbers) Reset() {
	*x = NotifyChangeNumbers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyChangeNumbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyChangeNumbers) ProtoMessage() {}

func (x *NotifyChangeNumbers) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyChangeNumbers.ProtoReflect.Descriptor instead.
func (*NotifyChangeNumbers) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyChangeNumbers) GetAll() []string {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *NotifyChangeNumbers) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *NotifyChangeNumbers) GetSenderMID() string {
	if x != nil {
		return x.SenderMID
	}
	return ""
}

var File_gbProto_proto protoreflect.FileDescriptor

var file_gbProto_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x43, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x54, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x3d, 0x0a, 0x09, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x54, 0x70, 0x22, 0x43, 0x0a, 0x09, 0x4d, 0x73, 0x67,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6c,
	0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x22, 0x40,
	0x0a, 0x0a, 0x52, 0x65, 0x63, 0x76, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x54, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x54, 0x70,
	0x22, 0x34, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x4d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x4d,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x41, 0x63,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x4c, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4d, 0x4c, 0x6f, 0x63, 0x22, 0x30, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x54, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x95, 0x01, 0x0a, 0x0b, 0x48, 0x61,
	0x6e, 0x64, 0x53, 0x68, 0x61, 0x63, 0x6b, 0x50, 0x31, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x73, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c, 0x6f,
	0x63, 0x22, 0xaf, 0x01, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x63, 0x6b, 0x50,
	0x32, 0x12, 0x24, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x4d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x4d, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x4d, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x73, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x48, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x73, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6c,
	0x6f, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x22, 0x7f,
	0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x4d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x4d, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4d,
	0x6c, 0x6f, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x22,
	0x80, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c,
	0x6f, 0x63, 0x22, 0x61, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x50, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x4d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x4d, 0x49, 0x44, 0x22, 0x7c, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4d, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d,
	0x6c, 0x6f, 0x63, 0x22, 0x5d, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c,
	0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d,
	0x49, 0x44, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x67, 0x62, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_gbProto_proto_rawDescOnce sync.Once
	file_gbProto_proto_rawDescData = file_gbProto_proto_rawDesc
)

func file_gbProto_proto_rawDescGZIP() []byte {
	file_gbProto_proto_rawDescOnce.Do(func() {
		file_gbProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_gbProto_proto_rawDescData)
	})
	return file_gbProto_proto_rawDescData
}

var file_gbProto_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_gbProto_proto_goTypes = []interface{}{
	(*ChatPayload)(nil),           // 0: main.ChatPayload
	(*Transport)(nil),             // 1: main.Transport
	(*MsgFormat)(nil),             // 2: main.MsgFormat
	(*RecvNotify)(nil),            // 3: main.RecvNotify
	(*SendNotify)(nil),            // 4: main.SendNotify
	(*ChatAck)(nil),               // 5: main.ChatAck
	(*SaveFormat)(nil),            // 6: main.SaveFormat
	(*HandShackP1)(nil),           // 7: main.HandShackP1
	(*HandShackP2)(nil),           // 8: main.HandShackP2
	(*ConnDataTransfer)(nil),      // 9: main.ConnDataTransfer
	(*HandshakeDeleteNotify)(nil), // 10: main.HandshakeDeleteNotify
	(*ChangeProfilePayload)(nil),  // 11: main.ChangeProfilePayload
	(*ChangeProfilePayloads)(nil), // 12: main.ChangeProfilePayloads
	(*NotifyChangeNumber)(nil),    // 13: main.NotifyChangeNumber
	(*NotifyChangeNumbers)(nil),   // 14: main.NotifyChangeNumbers
}
var file_gbProto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gbProto_proto_init() }
func file_gbProto_proto_init() {
	if File_gbProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gbProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandShackP1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandShackP2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnDataTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeDeleteNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeProfilePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeProfilePayloads); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyChangeNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyChangeNumbers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gbProto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gbProto_proto_goTypes,
		DependencyIndexes: file_gbProto_proto_depIdxs,
		MessageInfos:      file_gbProto_proto_msgTypes,
	}.Build()
	File_gbProto_proto = out.File
	file_gbProto_proto_rawDesc = nil
	file_gbProto_proto_goTypes = nil
	file_gbProto_proto_depIdxs = nil
}
